name: 'Podman Action'
description: 'Run commands in a container using Podman'

inputs:
  image:
    description: 'Container image to use'
    required: true
  run:
    description: 'Array of arguments to pass to the container runtime'
    required: true
  working-directory:
    description: 'Working directory where commands will be executed'
    required: false
    default: '.'
  entrypoint:
    description: 'Override the default entrypoint of the container image'
    required: false
    default: ''
  podman-args:
    description: 'Additional arguments to pass to podman run command'
    required: false

outputs:
  stdout:
    description: 'Standard output of the command'
  exit-code:
    description: 'Exit code of the command'

runs:
  using: 'node20'
  main: 'action.js'
